[package]
name = "trails"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7"
reqwest = { version = "0.11", features = ["blocking"] }
